# Model settings
transition: 'marginal'                          # uniform or marginal or planar
diffusion_steps: 500
n_layers: 5


# Extra features
extra_features: True
eigenfeatures: True
max_degree: 10  # for degree distribution
num_eigenvectors: 5
num_eigenvalues: 9
num_degree: 10  # for powers of adjacency matrix

extra_molecular_features: True

# Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
# At the moment (03/08), y contains quite little information
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

lambda_train: [1, 2, 5, 0]      # X, C, E, y

nu:
  x: 1
  c: 1
  e: 1
  y: 1

rev_proj: False
dropout: 0.1
dropout_in_and_out: False
cycle_features: True